# .github/workflows/docker-deploy.yml

name: Deploy to DigitalOcean with Docker
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/firesecure360:latest
          build-args: |
            EXPO_PUBLIC_GRAPHQL_ENDPOINT=${{ secrets.EXPO_PUBLIC_GRAPHQL_ENDPOINT }}

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/firesecure360:latest
            docker stop web-app || true
            docker rm web-app || true
            docker run -d \
              --name web-app \
              -p 80:80 \
              your-dockerhub-username/your-app:latest