# .github/workflows/docker-deploy.yml

name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/firesecure360-frontend:latest
          build-args: |
            EXPO_PUBLIC_GRAPHQL_ENDPOINT=${{ secrets.EXPO_PUBLIC_GRAPHQL_ENDPOINT }}

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/firesecure360-frontend:latest
            docker stop firesecure360-frontend || true
            docker rm firesecure360-frontend || true
            docker run -d \
              --name firesecure360-frontend \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/firesecure360-frontend:latest